FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["XExplorer.Api/XExplorer.Api.csproj", "XExplorer.Api/"]
RUN dotnet restore "XExplorer.Api/XExplorer.Api.csproj"
COPY . .
WORKDIR "/src/XExplorer.Api"
RUN dotnet build "XExplorer.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "XExplorer.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final 
ARG VERSION=latest
LABEL version=$VERSION
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "XExplorer.Api.dll"]
